services:

  # Prometheus Exporters ------------------------------
  elasticsearch-exporter:
    image: ${ELASTICSEARCH_EXPORTER_IMAGE}
    restart: always
    command:
      - "--es.uri=https://${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}@${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"
      - "--es.ssl-skip-verify"
      - "--es.indices"
      - "--collector.clustersettings"
      - "--collector.snapshots"
    ports:
      - "9114:9114"
    networks:
      - elastic

  logstash-exporter:
    image: ${LOGSTASH_EXPORTER_IMAGE}
    restart: always
    ports:
      - "9304:9304"
    command: [ "-logstash.host", "http://${LOGSTASH_HOST}:9600" ]
    networks:
      - elastic

networks:
  elastic:
    external: true
